In [2]:
pip install langchain_text_splitters

Collecting langchain_text_splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain_text_splitters) (1.4.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.0.16)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.8.8)
Requirement already satisfied: packaging>=23.2.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (3.1.1)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (2.34.2)
Requirement already satisfied: websockets>=15.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.25.0)
Requirement already satisfied: anyio in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (4.13.0)
Requirement already satisfied: certifi in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (2026.5.20)
Requirement already satisfied: httpcore==1.* in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (1.0.9)
Requirement already satisfied: idna in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (3.18)
Requirement already satisfied: h11>=0.16 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_text_splitters) (2.7.0)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: langchain_text_splitters
Successfully installed langchain_text_splitters-1.1.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter

d:\sudhendra\learning projects\GraphRAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
csv_path = Path("D:/sudhendra/learning projects/GraphRAG/data/apple23_extractedtxt.csv")

In [3]:
df = pd.read_csv(csv_path)

In [4]:
df.head()

   page                                               text
0     1  UNITED STATES\nSECURITIES AND EXCHANGE COMMISS...
1     2  Indicate by check mark whether the Registrant ...
2     3  Apple Inc.\nForm 10-K\nFor the Fiscal Year End...
3     4  This Annual Report on Form 10-K (“Form 10-K”) ...
4     5  Services\nAdvertising\nThe Company’s advertisi...

In [5]:
df = df.dropna(subset = "text")
df = df[df["text"].str.strip() != ""]
df.reset_index(drop = True, inplace = True)

In [6]:
len(df)

80

In [7]:
documents = []
for _, row in df.iterrows():
    documents.append({
        "page" : int(row["page"]),
        "text" : row["text"]
    })

documents[0]

{'page': 1,
 'text': 'UNITED STATES\nSECURITIES AND EXCHANGE COMMISSION\nWashington, D.C. 20549\nFORM 10-K\n(Mark One)\n☒    ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934\nFor the fiscal year ended September\xa030, 2023\nor\n☐    TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934\nFor the transition period from \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 to \xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0.\nCommission File Number: 001-36743\nApple Inc.\n(Exact name of Registrant as specified in its charter)\nCalifornia\n94-2404110\n(State or other jurisdiction\nof incorporation or organization)\n(I.R.S. Employer Identification No.)\nOne Apple Park Way\nCupertino, California\n95014\n(Address of principal executive offices)\n(Zip Code)\n(408) 996-1010\n(Registrant’s telephone number, including area code)\nSecurities registered pursuant to Section 12(b) of the Act:\nTitle of each class\nTrading \nsymbol(s)\nName of each exchange on which registered\nCommon Stock, $0.00001 par value per share\nAAPL\nThe Nasdaq Stock Market LLC\n1.375% Notes due 2024\n—\nThe Nasdaq Stock Market LLC\n0.000% Notes due 2025\n—\nThe Nasdaq Stock Market LLC\n0.875% Notes due 2025\n—\nThe Nasdaq Stock Market LLC\n1.625% Notes due 2026\n—\nThe Nasdaq Stock Market LLC\n2.000% Notes due 2027\n—\nThe Nasdaq Stock Market LLC\n1.375% Notes due 2029\n—\nThe Nasdaq Stock Market LLC\n3.050% Notes due 2029\n—\nThe Nasdaq Stock Market LLC\n0.500% Notes due 2031\n—\nThe Nasdaq Stock Market LLC\n3.600% Notes due 2042\n—\nThe Nasdaq Stock Market LLC\nSecurities registered pursuant to Section 12(g) of the Act:  None\nIndicate by check mark if the Registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act.\nYes\xa0\xa0☒\xa0\xa0\xa0\xa0\xa0No\xa0\xa0☐\nIndicate by check mark if the Registrant is not required to file reports pursuant to Section 13 or Section 15(d) of the Act.\nYes\xa0\xa0☐\xa0\xa0\xa0\xa0\xa0No\xa0\xa0☒\n'}

In [8]:
documents[8]

{'page': 9,
 'text': 'The Company has a large, global business with sales outside the U.S. representing a majority of the Company’s total net sales, \nand the Company believes that it generally benefits from growth in international trade. Substantially all of the Company’s \nmanufacturing is performed in whole or in part by outsourcing partners located primarily in China mainland, India, Japan, South \nKorea, Taiwan and Vietnam. Restrictions on international trade, such as tariffs and other controls on imports or exports of goods, \ntechnology or data, can materially adversely affect the Company’s operations and supply chain and limit the Company’s ability to \noffer and distribute its products and services to customers. The impact can be particularly significant if these restrictive measures \napply to countries and regions where the Company derives a significant portion of its revenues and/or has significant supply \nchain operations. Restrictive measures can require the Company to take various actions, including changing suppliers, \nrestructuring business relationships, and ceasing to offer third-party applications on its platforms. Changing the Company’s \noperations in accordance with new or changed restrictions on international trade can be expensive, time-consuming and \ndisruptive to the Company’s operations. Such restrictions can be announced with little or no advance notice and the Company \nmay not be able to effectively mitigate all adverse impacts from such measures. For example, tensions between governments, \nincluding the U.S. and China, have in the past led to tariffs and other restrictions being imposed on the Company’s business. If \ndisputes and conflicts further escalate in the future, actions by governments in response could be significantly more severe and \nrestrictive and could materially adversely affect the Company’s business. Political uncertainty surrounding trade and other \ninternational disputes could also have a negative effect on consumer confidence and spending, which could adversely affect the \nCompany’s business.\nMany of the Company’s operations and facilities, as well as critical business operations of the Company’s suppliers and contract \nmanufacturers, are in locations that are prone to earthquakes and other natural disasters. In addition, such operations and \nfacilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial \naccidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health \nissues, including pandemics such as the COVID-19 pandemic, and other events beyond the Company’s control. Global climate \nchange is resulting in certain types of natural disasters, such as droughts, floods, hurricanes and wildfires, occurring more \nfrequently or with more intense effects. Such events can make it difficult or impossible for the Company to manufacture and \ndeliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, and result \nin slowdowns and outages to the Company’s service offerings, and negatively impact consumer spending and demand in \naffected areas. Following an interruption to its business, the Company can require substantial recovery time, experience \nsignificant expenditures to resume operations, and lose significant sales. Because the Company relies on single or limited \nsources for the supply and manufacture of many critical components, a business interruption affecting such sources would \nexacerbate any negative consequences to the Company.\nThe Company’s operations are also subject to the risks of industrial accidents at its suppliers and contract manufacturers. While \nthe Company’s suppliers are required to maintain safe working environments and operations, an industrial accident could occur \nand could result in serious injuries or loss of life, disruption to the Company’s business, and harm to the Company’s reputation. \nMajor public health issues, including pandemics such as the COVID-19 pandemic, have adversely affected, and could in the \nfuture materially adversely affect, the Company due to their impact on the global economy and demand for consumer products; \nthe imposition of protective public safety measures, such as stringent employee travel restrictions and limitations on freight \nservices and the movement of products between regions; and disruptions in the Company’s operations, supply chain and sales \nand distribution channels, resulting in interruptions to the supply of current products and offering of existing services, and delays \nin production ramps of new products and development of new services.\nWhile the Company maintains insurance coverage for certain types of losses, such insurance coverage may be insufficient to \ncover all losses that may arise.\nGlobal markets for the Company’s products and services are highly competitive and subject to rapid technological \nchange, and the Company may be unable to compete effectively in these markets.\nThe Company’s products and services are offered in highly competitive global markets characterized by aggressive price \ncompetition and resulting downward pressure on gross margins, frequent introduction of new products and services, short \nproduct life cycles, evolving industry standards, continual improvement in product price and performance characteristics, rapid \nadoption of technological advancements by competitors, and price sensitivity on the part of consumers and businesses.\nThe Company’s ability to compete successfully depends heavily on ensuring the continuing and timely introduction of innovative \nnew products, services and technologies to the marketplace. The Company designs and develops nearly the entire solution for \nits products, including the hardware, operating system, numerous software applications and related services. As a result, the \nCompany must make significant investments in R&D. There can be no assurance these investments will achieve expected \nreturns, and the Company may not be able to develop and market new products and services successfully.\nApple Inc. | 2023 Form 10-K | 6\n'}

Chunking the Text

In [9]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1500,
    chunk_overlap = 250,
    separators = ["\n\n","\n","."," ",""]
)

chunks = []

for doc in documents:
    page_chunk = splitter.split_text(doc["text"])

    for i,chunk in enumerate(page_chunk):
        chunks.append({
            "page" : doc["page"],
            "chunk_id" : f"page_{doc['page']}_chunk_{i}",
            "text" : chunk
            })
        
        
chunks_df = pd.DataFrame(chunks)

chunks_df.head()

   page        chunk_id                                               text
0     1  page_1_chunk_0  UNITED STATES\nSECURITIES AND EXCHANGE COMMISS...
1     1  page_1_chunk_1  —\nThe Nasdaq Stock Market LLC\n1.375% Notes d...
2     2  page_2_chunk_0  Indicate by check mark whether the Registrant ...
3     2  page_2_chunk_1  any new or revised financial accounting standa...
4     2  page_2_chunk_2  day of the Registrant’s most recently complete...

In [10]:
len(chunks_df)

239

In [11]:
print(chunks_df.loc[0,"text"])

UNITED STATES
SECURITIES AND EXCHANGE COMMISSION
Washington, D.C. 20549
FORM 10-K
(Mark One)
☒    ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the fiscal year ended September 30, 2023
or
☐    TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the transition period from              to             .
Commission File Number: 001-36743
Apple Inc.
(Exact name of Registrant as specified in its charter)
California
94-2404110
(State or other jurisdiction
of incorporation or organization)
(I.R.S. Employer Identification No.)
One Apple Park Way
Cupertino, California
95014
(Address of principal executive offices)
(Zip Code)
(408) 996-1010
(Registrant’s telephone number, including area code)
Securities registered pursuant to Section 12(b) of the Act:
Title of each class
Trading
symbol(s)
Name of each exchange on which registered
Common Stock, $0.00001 par value per share
AAPL
The Nasdaq Stock Market LLC
1.375% Notes due 2024
—
The Nasdaq Stock Market LLC
0.000% Notes due 2025
—
The Nasdaq Stock Market LLC
0.875% Notes due 2025
—
The Nasdaq Stock Market LLC
1.625% Notes due 2026
—
The Nasdaq Stock Market LLC
2.000% Notes due 2027
—
The Nasdaq Stock Market LLC
1.375% Notes due 2029
—
The Nasdaq Stock Market LLC
3.050% Notes due 2029
—
The Nasdaq Stock Market LLC
0.500% Notes due 2031
—
The Nasdaq Stock Market LLC
3.600% Notes due 2042
—
The Nasdaq Stock Market LLC

In [12]:
chunks_df.sample(10)

     page         chunk_id                                               text
102    30  page_30_chunk_0  Item 8. \nFinancial Statements and Supplementa...
39     11  page_11_chunk_4  that can unexpectedly interfere with the inten...
41     12  page_12_chunk_0  The Company is exposed to the risk of write-do...
71     18  page_18_chunk_0  Financial Risks\nThe Company expects its quart...
166    57  page_57_chunk_0  PART IV\nItem 15. \nExhibit and Financial Stat...
144    49  page_49_chunk_0  Share-Based Compensation\nThe following table ...
214    71  page_71_chunk_3  (2) in the case of the 2013 Indenture, the hol...
32     10  page_10_chunk_2  and applications.\nThe Company’s business, res...
220    73  page_73_chunk_2  holders of debt securities of, in the case of ...
180    62  page_62_chunk_1  DESCRIPTION OF COMMON STOCK\nThe following is ...

In [13]:
output_chunks = Path("D:/sudhendra/learning projects/GraphRAG/data/apple23chunks.csv")

In [14]:
chunks_df.to_csv(output_chunks, index = False)
output_chunks

WindowsPath('D:/sudhendra/learning projects/GraphRAG/data/apple23chunks.csv')